name: Release

on:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    
    # Only deploy from master
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the ReactJS bundle
        run: yarn build
        env:
          REACT_APP_BACKEND_URL: "http://localhost:3001"
          PORT: 4000

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@39bbda1ce1fe24c69c6f57861b8038278d53688d
        with:
          #          pin-name: Ithil ${{ needs.bump_version.outputs.new_tag }}
          pin-name: Ithil
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      #      - name: Pin to Crust
      #        uses: crustio/ipfs-crust-action@v2.0.3
      #        continue-on-error: true
      #        timeout-minutes: 2
      #        with:
      #          cid: ${{ steps.upload.outputs.hash }}
      #          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'ithil.fi'
          RECORD_NAME: '_dnslink.app'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #          tag_name: ${{ needs.bump_version.outputs.new_tag }}
          #          release_name: Release ${{ needs.bump_version.outputs.new_tag }}
          release_name: Release
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`

            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.ithil.fi](https://app.ithil.fi).

            You can also access the Ithil Interface directly from an IPFS gateway.
            **BEWARE**: The Ithil interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.ithil.fi](https://app.ithil.fi).
            Your Ithil settings are never remembered across different URLs.

            IPFS gateways:
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)
